openapi: 3.0.0
info:
  version: '1.0'
  title: 'amc'
servers:
  - url: 'localhost:3000'
paths:
  /amc:
    get:
      operationId: listAMC
      responses:
        '200':
          description: 'List of AMC'
          content:
            application/json:
                schema:
                    type: array
                    items:                  
                        $ref: '#/components/schemas/AMC'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AMC:
      type: object
      properties:
        id:
            type: integer
            format: int64
        name:
            type: string
        description:
            type: string
        cin:
            type: string
        sebi_code:
            type: string
        background:
            type: string
        address:
            type: string
        website:
            type: string
            format: url
        contact_number:
            type: string
        contact_person:
            type: string
        email:
            type: string
            format: email
        product_category:
            type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        description:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []