openapi: 3.0.0
info:
  version: '1.0'
  title: 'Finalyca'
servers:
  - url: 'localhost:3000'
paths:
  /amc:
    get:
      operationId: listAMC
      responses:
        '200':
          description: 'List of AMC'
          content:
            application/json:
                schema:
                    type: array
                    items:                  
                        $ref: '#/components/schemas/AMC'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /scheme:
    get:
      operationId: listScheme
      parameters:
        - name: sebi_code
          in: query
          description: SEBI code of the AMC
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Returns list of offerings for an AMC'
          content:
            application/json:
                schema:
                    type: array
                    items:                  
                        $ref: '#/components/schemas/Scheme'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pms:
    get:
      operationId: listPMS
      parameters:
        - name: scheme_id
          in: query
          description: id of the scheme from Finalyca database
          required: true
          schema:
            type: integer
            format: int64
        - name: ts
          in: query
          description: date in string defined by RFC3339
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: 'Returns factsheet of the fund for the given date'
          content:
            application/json:
                schema:                 
                  $ref: '#/components/schemas/PMS'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /aif:
    get:
      operationId: listAIF
      parameters:
        - name: scheme_id
          in: query
          description: id of the scheme from Finalyca database
          required: true
          schema:
            type: integer
            format: int64
        - name: ts
          in: query
          description: date in string defined by RFC3339
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: 'Returns factsheet of the fund for the given date'
          content:
            application/json:
                schema:                 
                  $ref: '#/components/schemas/AIF'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AMC:
      type: object
      properties:
        id:
            type: integer
            format: int64
        name:
            type: string
        description:
            type: string
        cin:
            type: string
        sebi_code:
            type: string
        background:
            type: string
        address:
            type: string
        website:
            type: string
            format: url
        contact_number:
            type: string
        contact_person:
            type: string
        email:
            type: string
            format: email
        product_category:
            type: string
    Scheme:
      type: object
      properties:
        id:
            type: integer
            format: int64
        name:
            type: string
        description:
            type: string
        code:
            type: string
        scheme_category:
            type: string
            enum:
              - pms
              - aif
              - mf
              - ulip
        website:
            type: string
            format: url
    PMS:
      type: object
      properties:
        name:
            type: string
            description: Name of the scheme
        amc:
            type: string
            description: Name of the AMC
        as_on_date:
            type: string
            format: date
        net_assets:
            type: string
        fund_manager:
            type: string
        classification:
            type: string
        benchmark:
            type: string
        expense_ratio:
            type: string
        fee_structure:
            type: string
        exit_load:
            type: string
        investment_style:
            $ref: '#/components/schemas/investment_style_obj'
        fund_performance:
            $ref: '#/components/schemas/performance'
        benchmark_performance:
            $ref: '#/components/schemas/performance'
        std:
            type: number
            format: float
        alpha:
            type: number
            format: float
        beta:
            type: number
            format: float
        nav:
            type: number
            format: float
        aum:
            type: number
            format: float
        sectors:
            type: array
            items:                  
                $ref: '#/components/schemas/sectors'
        holdings:
            type: array
            items:                  
                $ref: '#/components/schemas/holdings'
    AIF:
      type: object
      properties:
        name:
            type: string
            description: Name of the scheme
        amc:
            type: string
            description: Name of the AMC
        as_on_date:
            type: string
            format: date
        net_assets:
            type: string
        fund_manager:
            type: string
        investment_theme:
            type: string
        commited_capital:
            type: number
            format: float
        drawdown_capital:
            type: number
            format: float
        launch_date:
            type: string
            format: date
        close_date:
            type: string
            format: date
        is_open_scheme:
            type: boolean
        category:
            type: string
        benchmark:
            type: string
        management_expense:
            type: string
        hurdle_rate:
            type: string
        performance_fees:
            type: string
        class_of_units:
            type: string
        fee_structure:
            type: string
        exit_load:
            type: string
        investment_style:
            $ref: '#/components/schemas/investment_style_obj'
        fund_performance:
            $ref: '#/components/schemas/performance'
        benchmark_performance:
            $ref: '#/components/schemas/performance'
        std:
            type: number
            format: float
        alpha:
            type: number
            format: float
        beta:
            type: number
            format: float
        nav:
            type: number
            format: float
        aum:
            type: number
            format: float
        sectors:
            type: array
            items:                  
                $ref: '#/components/schemas/sectors'
        holdings:
            type: array
            items:                  
                $ref: '#/components/schemas/holdings'
    sectors:
      type: object
      properties:
        name:
          type: string
        weight:
          type: number
          format: float
    holdings:
      type: object
      properties:
        name:
          type: string
        weight:
          type: number
          format: float
    investment_style_obj:
      type: object
      properties:
        large_cap:
          $ref: '#/components/schemas/investment_style_prop'
        mid_cap:
          $ref: '#/components/schemas/investment_style_prop'
        small_cap:
          $ref: '#/components/schemas/investment_style_prop'
    investment_style_prop:
      type: object
      properties:
        blend:
          type: number
          format: float
        growth:
          type: number
          format: float
        value:
          type: number
          format: float
    performance:
      type: object
      properties:
        3_months:
          type: number
          format: float
        6_months:
          type: number
          format: float
        1_yr:
          type: number
          format: float
        3_yr:
          type: number
          format: float
        5_yr:
          type: number
          format: float
        since_inception:
          type: number
          format: float
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        description:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []