USe [PMS_Base]

ALTER table [Transactions].[FundScreener]
ADD scheme_rolling_min_1_yr NUMERIC(18, 4) NULL,
scheme_rolling_max_1_yr NUMERIC(18, 4) NULL,
scheme_rolling_avg_1_yr NUMERIC(18, 4) NULL,
scheme_rolling_median_1_yr NUMERIC(18, 4) NULL,
scheme_rolling_positive_1_yr NUMERIC(18, 4) NULL,
scheme_rolling_neutral_1_yr NUMERIC(18, 4) NULL,
scheme_rolling_negative_1_yr NUMERIC(18, 4) NULL,
scheme_rolling_min_3_yr NUMERIC(18, 4) NULL,
scheme_rolling_max_3_yr NUMERIC(18, 4) NULL,
scheme_rolling_avg_3_yr NUMERIC(18, 4) NULL,
scheme_rolling_median_3_yr NUMERIC(18, 4) NULL,
scheme_rolling_positive_3_yr NUMERIC(18, 4) NULL,
scheme_rolling_neutral_3_yr NUMERIC(18, 4) NULL,
scheme_rolling_negative_3_yr NUMERIC(18, 4) NULL,
scheme_rolling_min_5_yr NUMERIC(18, 4) NULL,
scheme_rolling_max_5_yr NUMERIC(18, 4) NULL,
scheme_rolling_avg_5_yr NUMERIC(18, 4) NULL,
scheme_rolling_median_5_yr NUMERIC(18, 4) NULL,
scheme_rolling_positive_5_yr NUMERIC(18, 4) NULL,
scheme_rolling_neutral_5_yr NUMERIC(18, 4) NULL,
scheme_rolling_negative_5_yr NUMERIC(18, 4) NULL,
bm_rolling_min_1_yr NUMERIC(18, 4) NULL,
bm_rolling_max_1_yr NUMERIC(18, 4) NULL,
bm_rolling_avg_1_yr NUMERIC(18, 4) NULL,
bm_rolling_median_1_yr NUMERIC(18, 4) NULL,
bm_rolling_positive_1_yr NUMERIC(18, 4) NULL,
bm_rolling_neutral_1_yr NUMERIC(18, 4) NULL,
bm_rolling_negative_1_yr NUMERIC(18, 4) NULL,
bm_rolling_min_3_yr NUMERIC(18, 4) NULL,
bm_rolling_max_3_yr NUMERIC(18, 4) NULL,
bm_rolling_avg_3_yr NUMERIC(18, 4) NULL,
bm_rolling_median_3_yr NUMERIC(18, 4) NULL,
bm_rolling_positive_3_yr NUMERIC(18, 4) NULL,
bm_rolling_neutral_3_yr NUMERIC(18, 4) NULL,
bm_rolling_negative_3_yr NUMERIC(18, 4) NULL,
bm_rolling_min_5_yr NUMERIC(18, 4) NULL,
bm_rolling_max_5_yr NUMERIC(18, 4) NULL,
bm_rolling_avg_5_yr NUMERIC(18, 4) NULL,
bm_rolling_median_5_yr NUMERIC(18, 4) NULL,
bm_rolling_positive_5_yr NUMERIC(18, 4) NULL,
bm_rolling_neutral_5_yr NUMERIC(18, 4) NULL,
bm_rolling_negative_5_yr NUMERIC(18, 4) NULL
