USE [PMS_Base]
GO

/****** Object:  Table [Masters].[Industry_Classification] ******/

CREATE TABLE [Masters].[Industry_Classification](
	[MES_Code] varchar(100) NOT NULL,
	[Macro_Economic_Sector] varchar(200) NOT NULL,
	[Sect_Code] varchar(100) NOT NULL,
	[Sector] varchar(200) NOT NULL,
	[Ind_Code] varchar(100) NOT NULL,
	[Industry] varchar(200) NOT NULL,
	[Basic_Ind_Code] varchar(100) NOT NULL,
	[Basic_Industry] varchar(200) NOT NULL,
	[Sector_Id] int NULL,
	[Description] varchar(2000) NOT NULL,
	[Is_Deleted] [bit] NOT NULL,
	[Created_By] [bigint] NULL,
	[Created_Date] [datetime] NULL,
	[Updated_By] [bigint] NULL,
	[Updated_Date] [datetime] NULL,
	PRIMARY KEY CLUSTERED 
	(
		[Basic_Ind_Code] ASC
	)
) ON [PRIMARY]
GO



INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0101','Chemicals','IN010101','Chemicals & Petrochemicals','IN010101001','Commodity Chemicals',4,'Manufacturers of basic and industrial chemicals like synthetic fibers, films, organic and inorganic chemicals etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0101','Chemicals','IN010101','Chemicals & Petrochemicals','IN010101002','Specialty Chemicals',4,'Manufacturers of chemicals used in the manufacture of a variety of products, like fine chemicals, additives, advanced polymers, explosives, adhesives, printing inks, sealants, dyes, pigments, coatings etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0101','Chemicals','IN010101','Chemicals & Petrochemicals','IN010101003','Carbon Black',4,'Manufacturers of carbon black',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0101','Chemicals','IN010101','Chemicals & Petrochemicals','IN010101004','Dyes And Pigments',4,'Manufacturer, supplier and distributor of dyes and pigments',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0101','Chemicals','IN010101','Chemicals & Petrochemicals','IN010101005','Explosives',4,'Manufacturer, supplier and exporter of commercial explosives and explosive accessories',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0101','Chemicals','IN010101','Chemicals & Petrochemicals','IN010101006','Petrochemicals',4,'Manufacturer, supplier and distributor of petrochemical products like propylene oxide, propylene glycols and polyols etc. Also includes manufacturers of nylon, polyester and acrylic fibres, plastics (not covered under Plastic Products - Consumer under Consumer Discretionary and Plastic Products - Industrial under Manufacturing) etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0101','Chemicals','IN010101','Chemicals & Petrochemicals','IN010101007','Printing Inks',4,'Manufacturers and distributor of printing inks and allied material',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0101','Chemicals','IN010101','Chemicals & Petrochemicals','IN010101008','Trading - Chemicals',4,'Trading companies and distributors of chemicals',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0101','Chemicals','IN010101','Chemicals & Petrochemicals','IN010101009','Industrial Gases',4,'Producer or supplier of industrial gases',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0101','Chemicals','IN010102','Fertilizers & Agrochemicals','IN010102001','Fertilizers',4,'Manufacturers of fertilizers',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0101','Chemicals','IN010102','Fertilizers & Agrochemicals','IN010102002','Pesticides & Agrochemicals',4,'Manufacturers of agrochemicals and pesticides',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0102','Construction Materials','IN010203','Cement & Cement Products','IN010203001','Cement & Cement Products',14,'Manufacturer, supplier and distributor of cement, cement products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0102','Construction Materials','IN010204','Other Construction Materials','IN010204001','Other Construction Materials',14,'Other construction material such supplier of sand etc. It excludes companies dealing with granites, marbles, etc. which are classified as ''Furniture, Home Furnishing, Flooring'' under Consumer Discretionary',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010301','Ferrous Metals','IN010301001','Ferro & Silica Manganese',16,'Manufacturers and distributor of ferro silico manganese like ferro alloys, briquette, fly ash bricks etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010301','Ferrous Metals','IN010301002','Pig Iron',16,'Manufacturers and distributor of pig iron',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010301','Ferrous Metals','IN010301003','Sponge Iron',16,'Manufacturers and distributor of sponge iron',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010301','Ferrous Metals','IN010301004','Iron & Steel',16,'Manufacturers of Iron & steel',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010302','Non - Ferrous Metals','IN010302001','Aluminum',16,'Mining, processing, manufacturing and distributing the aluminum',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010302','Non - Ferrous Metals','IN010302002','Copper',16,'Producer and distributor of copper',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010302','Non - Ferrous Metals','IN010302003','Zinc',16,'Producer and distributor of zinc',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010302','Non - Ferrous Metals','IN010302004','Precious Metals',16,'Mining, manufacturing and distributing precious materials like gold, silver, platinum etc. Includes investment trusts where underlying is gold or similar precious metals',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010303','Diversified Metals','IN010303001','Diversified Metals',16,'Companies engaged in manufacturing and mining of diversified metals',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010304','Minerals & Mining','IN010304001','Industrial Minerals',16,'Mining, producing and distributing industrial materials (excluding Coal which has been classified under ''Energy'')',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010305','Metals & Minerals Trading','IN010305001','Trading - Metals',16,'Trading companies and distributors of metals (excluding precious metals)',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0103','Metals & Mining','IN010305','Metals & Minerals Trading','IN010305002','Trading - Minerals',16,'Trading companies and distributors of industrial minerals (excluding Coal trading which has been classified under ''Energy'')',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0104','Forest Materials','IN010401','Paper, Forest & Jute Products','IN010401001','Paper & Paper Products',26,'Manufacturers of paper, paper boards etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0104','Forest Materials','IN010401','Paper, Forest & Jute Products','IN010401002','Forest Products',26,'Companies dealing with Timber, Wood, Soil, Pulp, Firewood, Cork, Shellac, Cross Laminated Timber excluding plywood and laminates which is classified as ''Furniture, Home Furnishing, Flooring'' under Consumer Discretionary',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN01','Commodities','IN0104','Forest Materials','IN010401','Paper, Forest & Jute Products','IN010401003','Jute & Jute Products',26,'Manufacturers of jute and jute products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0201','Automobile and Auto Components','IN020101','Automobiles','IN020101001','Passenger Cars & Utility Vehicles',15,'Manufacturer of passenger /utility vehicles including car, bus, taxis, auto rickshaws etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0201','Automobile and Auto Components','IN020101','Automobiles','IN020101002','2/3 Wheelers',15,'Manufacturers of motorcycles, scooters, three-wheelers and bicycles',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0201','Automobile and Auto Components','IN020101','Automobiles','IN020101003','Trading - Automobiles',15,'Trading and distribution of passenger cars, utility vehicles, 2/3 wheelers',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0201','Automobile and Auto Components','IN020102','Auto Components','IN020102001','Auto Components & Equipments',15,'Manufacturers and distributors of accessories for automobiles',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0201','Automobile and Auto Components','IN020102','Auto Components','IN020102002','Batteries - Automobile',15,'Manufacturer of automobiles batteries',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0201','Automobile and Auto Components','IN020102','Auto Components','IN020102003','Fastener',15,'Manufacturer of fastener for vehicles',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0201','Automobile and Auto Components','IN020102','Auto Components','IN020102004','Gas Cylinders',15,'Manufacturer of gas cylinders for automobile',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0201','Automobile and Auto Components','IN020102','Auto Components','IN020102005','Trading - Auto Ancillaries',15,'Trading and distribution of auto components',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0201','Automobile and Auto Components','IN020102','Auto Components','IN020102006','Tyres & Rubber Products',15,'Manufacturers and distributors of tyres and rubber products for automobile',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201001','Air Conditioner',17,'Manufacturers and distributors of air conditioners',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201002','Cycles',17,'Manufacturers and distributors of bicycles and tricycles',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201003','Consumer Electronics',17,'Manufacturers and distributor of consumer electronics like television, video cassette recorder, DVD player, audio equipments, games etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201004','Furniture, Home Furnishing, Flooring',17,'Manufacturers and distributor of furniture, carpets, ceramic tiles, granite, marble etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201005','Gems, Jewellery And Watches',17,'Manufacturers and distributor of gems, jewellery, watches and other luxury goods and accessories',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201006','Glass - Consumer',17,'Manufacturers and distributor of consumer glass products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201007','Household Appliances',17,'Manufacturers of electric household appliances like juicers, food processors, microwave ovens etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201008','Houseware',17,'Manufacturers and distributors of other household durable products like cookware, cutlery, utensils and consumer specialties not classified otherwise',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201009','Leather And Leather Products',17,'Manufacturers and distributors of leather products such as belt, leather bags etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201010','Leisure Products',17,'Manufacturers of leisure products and equipment including sports equipment, gift articles etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201011','Plastic Products - Consumer',17,'Manufacturers and distributor of plastic products used in households such as suitcase, briefcase and other consumer plastic products not covered under ''Houseware'' above',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201012','Plywood Boards/ Laminates',17,'Manufacturers and distributor of plywood, laminates etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201013','Sanitary Ware',17,'Manufacturer of sanitary ware like ceramic plumbing fixtures (as sinks, lavatories, or toilet bowls)',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201014','Toys',17,'Manufacturers and distributors of toys, games etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201015','Paints',17,'Manufacturers and distributors of interior and exterior paints',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201016','Diversified Consumer Products',17,'Any other consumer products not covered above',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0202','Consumer Durables','IN020201','Consumer Durables','IN020201017','Footwear',17,'Companies engaged in manufacturing, trading and distribution of all types of footwear and related accessories',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0203','Textiles','IN020301','Textiles & Apparels','IN020301001','Garments & Apparels',5,'Manufacturers & distributors of apparels/ garments',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0203','Textiles','IN020301','Textiles & Apparels','IN020301002','Other Textile Products',5,'Manufacturers & distributors of textiles, fabrics, yarn, silk yarn, blended and texturized yarn and related products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0203','Textiles','IN020301','Textiles & Apparels','IN020301003','Trading - Textile Products',5,'Trading and Distribution of ''garments & apparels'' and ''other textile products'' where a revenue from each segment cannot be determined separately',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0204','Media, Entertainment & Publication','IN020401','Media','IN020401001','Advertising & Media Agencies',10,'Companies providing advertising, public relations and marketing services. It also includes billboard providers and telemarketers.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0204','Media, Entertainment & Publication','IN020401','Media','IN020401002','Electronic Media',10,'Publisher of newspapers, magazines and other periodicals through electronic medium',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0204','Media, Entertainment & Publication','IN020401','Media','IN020401003','Web based media and service',10,'Companies engaged in providing social media, search engines, platforms for networking etc. Excludes companies operating in online shopping classified under E-Retail/ E-Commerce and companies providing online directory of suppliers and potential buyers for various products/ merchandise classified under Internet & Catalogue Retail',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0204','Media, Entertainment & Publication','IN020401','Media','IN020401004','Print Media',10,'Publisher of newspapers, magazines and other periodicals through print medium',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0204','Media, Entertainment & Publication','IN020402','Entertainment','IN020402001','Film Production, Distribution & Exhibition',10,'Producers and distributors of movies. Includes theatres and auditoriums',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0204','Media, Entertainment & Publication','IN020402','Entertainment','IN020402002','Digital Entertainment',10,'Producers and distributors of movies and other entertainment related contents through digital, Over the Top (OTT) platform.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0204','Media, Entertainment & Publication','IN020402','Entertainment','IN020402003','Media & Entertainment',10,'Producers and distributors of entertainment products and services. It includes companies engaged in the production, distribution and screening of television shows, producers and distributors of music and sports teams. It excludes production and distribution of movies which is classified under ''Film Production, Distribution & Exhibition''.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0204','Media, Entertainment & Publication','IN020402','Entertainment','IN020402004','TV Broadcasting & Software Production',10,'Owners of TV channels, includes broadcasting of TV shows and cable TV operators and DTH service providers',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0204','Media, Entertainment & Publication','IN020403','Printing & Publication','IN020403001','Printing & Publication',10,'Companies providing service of commercial printing, publication of books, commercial documents etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0205','Realty','IN020501','Realty','IN020501001','Residential, Commercial Projects',14,'Companies engaged in development and construction of residential/ commercial (offices/shops etc.) properties',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0205','Realty','IN020501','Realty','IN020501002','Real Estate related services',14,'Companies engaged in providing real estate related services like real estate agents',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0205','Realty','IN020501','Realty','IN020501003','Real Estate Investment Trusts (REITs)',14,'Companies or Trusts engaged in ownership, acquisition, development, management and operation of real estate',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020601','Leisure Services','IN020601001','Hotels & Resorts',1,'Owners and operators of hotels, resorts etc. Includes investment trusts where underlying is ''Hotels and Resorts''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020601','Leisure Services','IN020601002','Restaurants',1,'Owners and operators of restaurants, recreation clubs, bars, coffee shops, fast food, catering service etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020601','Leisure Services','IN020601003','Amusement Parks/ Other Recreation',1,'Owners and operators of amusement parks, Casinos and other recreation facilities not covered above',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020601','Leisure Services','IN020601004','Wellness',1,'Owners and operators of wellness facilities such as gymnasium, yoga center, beauty parlours, salons etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020601','Leisure Services','IN020601005','Tour, Travel Related Services',1,'Companies engaged into provision of tour, travel related services. It includes tour operators, ticketing, visa processing, hotel and vehicle booking etc. It includes companies that provide such service through digital medium',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020602','Other Consumer Services','IN020602001','Education',1,'Any stream of education (including IT education or any specialized training) provided in classroom',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020602','Other Consumer Services','IN020602002','E-Learning',1,'Any stream of education (including IT education or any specialized training) provided through medium other than classroom',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020602','Other Consumer Services','IN020602003','Food Storage Facilities',1,'Companies engaged in providing food storage facility',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020602','Other Consumer Services','IN020602004','Other Consumer Services',1,'Companies providing other consumer services not classified elsewhere. It includes event managers, security services, housekeeping services etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020603','Retailing','IN020603001','Speciality Retail',1,'Owners and operators of retail store comprising a single class of goods such as apparels, electronics, stationary etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020603','Retailing','IN020603002','Pharmacy Retail',1,'Companies engaged in sale of pharmaceutical, provision of health related products and services through electronic medium',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020603','Retailing','IN020603003','Diversified Retail',1,'Owners and operators of stores offering multiple range of product categories (department stores)',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020603','Retailing','IN020603004','E-Retail/ E Commerce',1,'Companies that earn significant revenue from provision of products or services predominantly through electronic medium such as internet.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020603','Retailing','IN020603005','Internet & Catalogue Retail',1,'Companies providing online directory of suppliers and potential buyers for various products/ merchandise',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN02','Consumer Discretionary','IN0206','Consumer Services','IN020603','Retailing','IN020603006','Distributors',1,'Distributors and wholesalers of general merchandise not classified elsewhere',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN03','Energy','IN0301','Oil, Gas & Consumable Fuels','IN030101','Gas','IN030101001','Gas Transmission/Marketing',2,'Companies engaged in marketing and/ or transportation of gases',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN03','Energy','IN0301','Oil, Gas & Consumable Fuels','IN030101','Gas','IN030101002','Industrial Gas',2,'Producer or supplier of industrial gases',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN03','Energy','IN0301','Oil, Gas & Consumable Fuels','IN030101','Gas','IN030101003','LPG/CNG/PNG/LNG Supplier',2,'Companies engaged in distribution of LPG, CNG, PNG and LNG',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN03','Energy','IN0301','Oil, Gas & Consumable Fuels','IN030101','Gas','IN030101004','Trading - Gas',2,'Companies engaged in the activity of trading in gas',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN03','Energy','IN0301','Oil, Gas & Consumable Fuels','IN030102','Oil','IN030102001','Oil Exploration & Production',2,'Companies engaged in the exploration and production of oil',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN03','Energy','IN0301','Oil, Gas & Consumable Fuels','IN030102','Oil','IN030102002','Offshore Support Solution Drilling',2,'Companies providing offshore drilling services to oil companies',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN03','Energy','IN0301','Oil, Gas & Consumable Fuels','IN030102','Oil','IN030102003','Oil Storage & Transportation',2,'Companies engaged in providing storage and transportation facility for oil companies',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN03','Energy','IN0301','Oil, Gas & Consumable Fuels','IN030102','Oil','IN030102004','Oil Equipment & Services',2,'Manufacturers of equipment for and providers of services to the oil and gas industry',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN03','Energy','IN0301','Oil, Gas & Consumable Fuels','IN030103','Petroleum Products','IN030103001','Refineries & Marketing',2,'Companies engaged in the refining and marketing of oil, gas and petroleum products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN03','Energy','IN0301','Oil, Gas & Consumable Fuels','IN030103','Petroleum Products','IN030103002','Lubricants',2,'Manufacturers and distributors of lubricants',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN03','Energy','IN0301','Oil, Gas & Consumable Fuels','IN030104','Consumable Fuels','IN030104001','Coal',2,'Companies engaged in exploration, mining, trading and distribution of coal, coke and lignite',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040101','Agricultural Food & other Products','IN040101001','Edible Oil',9,'Producers and distributors of edible oil',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040101','Agricultural Food & other Products','IN040101002','Sugar',9,'Producers and distributors of sugar and allied products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040101','Agricultural Food & other Products','IN040101003','Tea & Coffee',9,'Producers and distributors of tea and coffee',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040101','Agricultural Food & other Products','IN040101004','Other Agricultural Products',9,'Producers and distributors of agricultural products not classified elsewhere',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040102','Beverages','IN040102001','Breweries & Distilleries',9,'Manufacturers of alcoholic beverages. Includes distillers',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040102','Beverages','IN040102002','Other Beverages',9,'Manufacturers of non-alcoholic beverages',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040103','Cigarettes & Tobacco Products','IN040103001','Cigarettes & Tobacco Products',9,'Manufacturers and distributors of cigarettes and other tobacco products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040104','Food Products','IN040104001','Animal Feed',9,'Manufacturers and distributors of animal feed',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040104','Food Products','IN040104002','Dairy Products',9,'Producers and distributors of dairy products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040104','Food Products','IN040104003','Other Food Products',9,'Producers and distributors of other food products not classified elsewhere',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040104','Food Products','IN040104004','Packaged Foods',9,'Producers & distributors of packaged foods including biscuits, chocolates, chips etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040105','Personal Products','IN040105001','Personal Care',9,'Manufacturers and distributors of personal products such as toothpaste, shampoo, perfume, cosmetics etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040106','Household Products','IN040106001','Household Products',9,'Manufacturers and distributors of household products such as aluminum foils, detergents, matchstick, paper tissues, soaps etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040106','Household Products','IN040106002','Batteries',9,'Manufacturers and distributors of batteries used in home appliances. Excludes automobiles batteries classified under ''Consumer Discretionary''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040106','Household Products','IN040106003','Photographic Products',9,'Manufacturers and distributors of photographic products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040106','Household Products','IN040106004','Stationary',9,'Manufacturers and distributors of stationary such as pen, pencil, notebooks etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN04','Fast Moving Consumer Goods','IN0401','Fast Moving Consumer Goods','IN040107','Diversified FMCG','IN040107001','Diversified FMCG',9,'Companies engaged into multiple FMCG products, where no single business segment contributes more than 50% of companies'' total revenue and two or more segments each contributes at least 20% of total revenue',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050101','Finance','IN050101001','Financial Institution',11,'Financial Institutions as defined under Section 4(1) of the Companies Act, 1956',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050101','Finance','IN050101002','Housing Finance Company',11,'Companies providing loan for buying housing and commercial properties',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050101','Finance','IN050101003','Investment Company',11,'Companies which earn major revenue from interest, capital appreciation from investments made. It does not include rental income which is classified under ''Diversified Commercial Services''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050101','Finance','IN050101004','Non Banking Financial Company (NBFC)',11,'Non-Banking Financial Company (NBFC) as may be specified by the Reserve Bank of India (RBI)',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050101','Finance','IN050101005','Other Financial Services',11,'Companies providing financial services not covered elsewhere under ''Financial Services''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050101','Finance','IN050101006','Holding Company',11,'Holding companies with holding of 51% or more in other company',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050102','Banks','IN050102001','Public Sector Bank',11,'Banks sponsored by Central or State government in India categorized as public sector bank by Reserve Bank of India (RBI)',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050102','Banks','IN050102002','Private Sector Bank',11,'Banks categorized as private sector banks by Reserve Bank of India (RBI)',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050102','Banks','IN050102003','Other Bank',11,'Other banks not classified under Public Sector Bank and Private Sector Bank above. Includes foreign banks, payment banks, small banks etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050103','Capital Markets','IN050103001','Asset Management Company',11,'Companies engaged in mutual fund activities i.e., companies operating mutual funds, open-end mutual funds, closed-end mutual funds etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050103','Capital Markets','IN050103002','Depositories, Clearing Houses and Other Intermediaries',11,'Companies providing depository services. Includes clearing houses/ clearing corporations, registrar/ share transfer agents, custodians etc. which are not covered elsewhere under ''Capital Markets''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050103','Capital Markets','IN050103003','Financial Products Distributor',11,'Companies engaged into distribution of financial products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050103','Capital Markets','IN050103004','Ratings',11,'Companies providing ratings service',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050103','Capital Markets','IN050103005','Exchange and Data Platform',11,'Companies providing platform for trading of equity, commodity, currency, fixed income securities, power etc. are classified under ''Exchange Platform''. Companies providing data vending/ data dissemination are classified under ''Data Platform''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050103','Capital Markets','IN050103006','Stockbroking & Allied',11,'Companies engaged in providing brokerage services and other allied activities such as investment advisory services etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050103','Capital Markets','IN050103007','Other Capital Market related Services',11,'Other Capital Market related Services not classified elsewhere above',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050104','Insurance','IN050104001','General Insurance',23,'Companies providing general insurance',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050104','Insurance','IN050104002','Life Insurance',23,'Companies providing life insurance',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050104','Insurance','IN050104003','Other Insurance Companies',23,'Insurance companies offering multiple line of insurance such as life insurance, general insurance, medical insurance, etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050104','Insurance','IN050104004','Insurance Distributors',23,'Companies engaged into distribution of insurance products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN05','Financial Services','IN0501','Financial Services','IN050105','Financial Technology (Fintech)','IN050105001','Financial Technology (Fintech)',11,'Fintechs providing services like banking, payment processing, brokerage, aggregation and distribution of financial products and services',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN06','Healthcare','IN0601','Healthcare','IN060101','Pharmaceuticals & Biotechnology','IN060101001','Pharmaceuticals',13,'Manufacturers and distributors of pharmaceuticals and companies engaged in research & development of pharmaceuticals',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN06','Healthcare','IN0601','Healthcare','IN060101','Pharmaceuticals & Biotechnology','IN060101002','Biotechnology',13,'Companies engaged in the development, manufacturing or marketing and distribution of products based on biotechnology',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN06','Healthcare','IN0601','Healthcare','IN060102','Healthcare Equipment & Supplies','IN060102001','Medical Equipment & Supplies',13,'Manufacturers and distributors of medical equipments such as blood pressure monitoring machine, X-Ray machines, MRI scanners, and supplies such as injection needles, syringe, gloves etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN06','Healthcare','IN0601','Healthcare','IN060103','Healthcare Services','IN060103001','Hospital',13,'Owners and operators of health care facilities. It includes hospitals, nursing homes and veterinary hospitals. Includes investment trusts where underlying is ''Hospitals''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN06','Healthcare','IN0601','Healthcare','IN060103','Healthcare Services','IN060103002','Healthcare Service Provider',13,'Owners and operators of diagnostic services such as pathological laboratories, X-Ray and MRI scan centers, etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN06','Healthcare','IN0601','Healthcare','IN060103','Healthcare Services','IN060103003','Healthcare Research, Analytics & Technology',13,'Companies providing healthcare research and analytics related services',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0701','Construction','IN070101','Construction','IN070101001','Civil Construction',14,'Companies engaged in designing, construction and maintenance of roads, bridges, canals, dams etc. It excludes companies engaged in construction of residential and commercial buildings which are classified as ''Realty'' under ''Consumer Discretionary''. Includes investment trusts where underlying is ''Civil Construction''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0701','Construction','IN070101','Construction','IN070101002','Engineering, Designing & Construction',14,'Companies engaged into Engineering, procurement and construction (EPC) projects',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070201','Aerospace & Defense','IN070201001','Aerospace & Defense',12,'Manufacturers of civil and military aerospace and equipments, defense equipments, defense electronics and products thereof',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070202','Agricultural, Commercial & Construction Vehicles','IN070202001','Tractors',15,'Manufacturers and distributors of tractors and other farm vehicles',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070202','Agricultural, Commercial & Construction Vehicles','IN070202002','Commercial Vehicles',15,'Manufacturers and distributors of commercial vehicles as trucks, dumpers etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070202','Agricultural, Commercial & Construction Vehicles','IN070202003','Construction Vehicles',15,'Manufacturers and distributors of construction vehicles like cranes, bulldozers etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070203','Electrical Equipment','IN070203001','Heavy Electrical Equipment',12,'Manufacturers and distributors of power generating equipment and other heavy electrical equipment such as power turbines, transmission towers, heavy electrical machinery',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070203','Electrical Equipment','IN070203002','Other Electrical Equipment',12,'Manufactures and distributors of electric cables and wires and other electrical components or equipment not classified under Heavy Electrical Equipment',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070204','Industrial Manufacturing','IN070204001','Elevators',12,'Manufacturer of elevators and escalators',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070204','Industrial Manufacturing','IN070204002','Engineering & Construction products',12,'Manufacturers and distributors of engineering and construction related products not covered elsewhere',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070204','Industrial Manufacturing','IN070204003','Industrial Electronics',12,'Manufacturers and distributor of industrial electronics like CC TV surveillance system, access control system, fire alarm System, multi apartment video door phones, video door phones, intruder alarm System, fingerprint locks, and remote managed services etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070204','Industrial Manufacturing','IN070204004','Industrial Equipments',12,'Manufacturers and distributor of industrial equipment not covered elsewhere',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070204','Industrial Manufacturing','IN070204005','Railway Wagons',9,'Manufacturers of railway wagons and EMU coaches',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070204','Industrial Manufacturing','IN070204006','Ship Building & Allied Services',12,'Companies engaged in ship building and providing allied services',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070204','Industrial Manufacturing','IN070204007','Industrial Machinery',12,'Manufacturers and distributors of industrial machinery not covered elsewhere',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205001','Abrasives',12,'Manufactures and distributors of abrasives',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205002','Bearings',12,'Manufactures and distributors of bearings. Excludes bearings used for automobiles which are classified as ''Auto Components & Equipments'' under Consumer Discretionary',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205003','Cables - Electricals',12,'Manufacturers and distributors of electrical cables/ wires. Excludes telecom cables which are classified as ''Telecom - Equipment & Accessories'' under ''Telecommunication''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205004','Castings & Forgings',16,'Manufacturers and distributors of castings and forgings. Excludes companies generating majority revenue from automobile segment and they are classified as ''Auto Components & Equipments'' classified under ''Consumer Discretionary''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205005','Compressors & Pumps',12,'Manufacturers and distributors of compressors and pumps',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205006','Diesel Engines',12,'Manufacturers and distributors of diesel engines. Excludes engines used for automobiles which are classified as ''Auto Components & Equipments'' under Consumer Discretionary',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205007','Electrodes',12,'Manufacturers and distributors of electrodes',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205008','Packaging',26,'Manufacturers and distributors of packaging materials such as cardboard, bags, boxes, cans, drums, bottles and jars and glass',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205009','Plastic Products - Industrial',26,'Manufacturers and distributors of industrial plastic products such as plastic pipes etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205010','Refractories',12,'Manufacturers and distributors of refractories',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205011','Rubber',26,'Manufacturers and distributors of rubber and rubber products. Excludes companies classified as ''Tyers & Rubber Products'' under ''Consumer Discretionary''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205012','Other Industrial Products',12,'Manufacturers and distributors of other industrial products not classified elsewhere',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205013','Glass - Industrial',26,'Manufacturers and distributors of industrial glasses. It excludes consumer glass classified under ''Consumer Discretionary''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205014','Aluminium, Copper & Zinc Products',16,'Manufacturers and distributors of aluminum, copper and zinc products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN07','Industrials','IN0702','Capital Goods','IN070205','Industrial Products','IN070205015','Iron & Steel Products',16,'Manufacturers and distributors of iron and steel products',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN08','Information Technology','IN0801','Information Technology','IN080101','IT - Software','IN080101001','Computers - Software & Consulting',3,'Companies engaged in software development, IT consulting and data analytics',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN08','Information Technology','IN0801','Information Technology','IN080101','IT - Software','IN080101002','Software Products',3,'Companies engaged in development of software products that can be commonly used by individuals and corporates',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN08','Information Technology','IN0801','Information Technology','IN080102','IT - Services','IN080102001','IT Enabled Services',3,'Companies engaged in providing services for business automation through provision of IT infrastructure.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN08','Information Technology','IN0801','Information Technology','IN080103','IT - Hardware','IN080103001','Computers Hardware & Equipments',3,'Manufactures and distributors of computer hardware and equipments such as personal computers, laptops, servers, motherboards, networking equipments, printers, photo copiers etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090101','Engineering Services','IN090101001','Dredging',1,'Companies providing dredging and related services',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090102','Transport Services','IN090102001','Airline',1,'Owners and operators of commercial airlines',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090102','Transport Services','IN090102002','Logistics Solution Provider',1,'Companies providing logistic services, courier, movers & packers etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090102','Transport Services','IN090102003','Railways',1,'Companies providing passenger or cargo transportation through railways',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090102','Transport Services','IN090102004','Road Transport',1,'Companies providing passenger or cargo transportation through roads',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090102','Transport Services','IN090102005','Shipping',1,'Companies providing passenger or cargo transportation through marine (shipping)',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090102','Transport Services','IN090102006','Transport Related Services',1,'Other transport related service not covered elsewhere',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090103','Transport Infrastructure','IN090103001','Airport & Airport services',1,'Owners and operators of airports and companies providing airport related services',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090103','Transport Infrastructure','IN090103002','Port & Port services',1,'Owners and operators of marine ports and related services like marine engineering services',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090103','Transport Infrastructure','IN090103003','Toll bridge operator',1,'Operators of bridge, highway, toll bridges etc. Does not include companies engaged into construction of road, bridges and highways which are classified as ''Civil Construction'' under ''Manufacturing''',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090104','Commercial Services & Supplies','IN090104001','Trading & Distributors',1,'Companies engaged in trading and distribution of goods not covered elsewhere',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090104','Commercial Services & Supplies','IN090104002','Consulting Services',1,'Companies engaged in providing consulting services',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090104','Commercial Services & Supplies','IN090104003','Data Processing Services',1,'Companies engaged in providing commercial electronic data processing services',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090104','Commercial Services & Supplies','IN090104004','Diversified Commercial Services',1,'Companies providing commercial and consumer services not classified elsewhere. Includes, employment and related services, environmental services and pollution control services, other security services, renting and leasing services, trade and commission agent services etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN09','Services','IN0901','Services','IN090104','Commercial Services & Supplies','IN090104005','Business Process Outsourcing (BPO)/ Knowledge Process Outsourcing (KPO)',1,'Companies engaged in providing Business Process Outsourcing (BPO)/ Knowledge Process Outsourcing (KPO) services',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN10','Telecommunication','IN1001','Telecommunication','IN100101','Telecom - Services','IN100101001','Telecom - Cellular & Fixed line services',10,'Companies providing fixed line and cellular telecom services',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN10','Telecommunication','IN1001','Telecommunication','IN100101','Telecom - Services','IN100101002','Telecom - Infrastructure',10,'Companies engaged into provision of telecom instruments and telecom related infrastructure services.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN10','Telecommunication','IN1001','Telecommunication','IN100101','Telecom - Services','IN100101003','Other Telecom Services',10,'Companies engaged into provision of broad band internet service and other telecom related services not covered elsewhere',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN10','Telecommunication','IN1001','Telecommunication','IN100102','Telecom - Equipment & Accessories','IN100102001','Telecom - Equipment & Accessories',10,'Manufacturers and distributors of telecom equipments, cables and other accessories. Includes investment trusts where underlying is telecom equipment such as telephone instruments',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN11','Utilities','IN1101','Power','IN110101','Power','IN110101001','Electric Utilities',2,'Companies engaged into production and distribution of thermal, solar, hydro and wind power. Includes investment trusts where underlying is power generation and distribution',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN11','Utilities','IN1101','Power','IN110101','Power','IN110101002','Power Trading',11,'Companies engaged into trading of electricity',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN11','Utilities','IN1101','Power','IN110101','Power','IN110101003','Power - Transmission',12,'Companies engaged into transmission or distribution of electricity. Includes investment trusts where underlying is power transmission',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN11','Utilities','IN1102','Utilities','IN110201','Other Utilities','IN110201001','Water Supply & Management',12,'Companies engaged into water supply and management',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN11','Utilities','IN1102','Utilities','IN110201','Other Utilities','IN110201002','Waste Management',1,'Companies engaged into waste management',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN11','Utilities','IN1102','Utilities','IN110201','Other Utilities','IN110201003','Emergency Services',1,'Companies engaged into providing emergency services like fire brigade, flood management etc.',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN11','Utilities','IN1102','Utilities','IN110201','Other Utilities','IN110201004','Multi Utilities',24,'Companies providing multiple lines of utilities',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN11','Utilities','IN1102','Utilities','IN110201','Other Utilities','IN110201005','Other Utilities',24,'Companies providing utilities not covered elsewhere',0,NULL,GetDate(),NULL,NULL)
INSERT INTO [Masters].[Industry_Classification] VALUES('IN12','Diversified','IN1201','Diversified','IN120101','Diversified','IN120101001','Diversified',24,'Companies engaged into multiple business segment, where no single business segment contributes more than 50% of companies'' total revenue and two or more segments each contributes at least 20% of total revenue',0,NULL,GetDate(),NULL,NULL)

GO


/*********************** Adding CMOTS Sector Code and CMOTS Sector Values *****************************/

ALTER TABLE [Masters].[Industry_Classification] ADD [CM_Sector_Code] varchar(20) NULL
GO

ALTER TABLE [Masters].[Industry_Classification] ADD [CM_Sector_Name] varchar(200) NULL
GO


Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '14', [CM_Sector_Name] = 'Chemicals' Where [Basic_Ind_Code] = 'IN010101001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '14', [CM_Sector_Name] = 'Chemicals' Where [Basic_Ind_Code] = 'IN010101002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '14', [CM_Sector_Name] = 'Chemicals' Where [Basic_Ind_Code] = 'IN010101003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '14', [CM_Sector_Name] = 'Chemicals' Where [Basic_Ind_Code] = 'IN010101004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '14', [CM_Sector_Name] = 'Chemicals' Where [Basic_Ind_Code] = 'IN010101005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '45', [CM_Sector_Name] = 'Petrochemicals' Where [Basic_Ind_Code] = 'IN010101006'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '14', [CM_Sector_Name] = 'Chemicals' Where [Basic_Ind_Code] = 'IN010101007'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '14', [CM_Sector_Name] = 'Chemicals' Where [Basic_Ind_Code] = 'IN010101008'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '14', [CM_Sector_Name] = 'Chemicals' Where [Basic_Ind_Code] = 'IN010101009'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '25', [CM_Sector_Name] = 'Fertilizers' Where [Basic_Ind_Code] = 'IN010102001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '1', [CM_Sector_Name] = 'Agro Chemicals' Where [Basic_Ind_Code] = 'IN010102002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '11', [CM_Sector_Name] = 'Cement' Where [Basic_Ind_Code] = 'IN010203001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '16', [CM_Sector_Name] = 'Construction' Where [Basic_Ind_Code] = 'IN010204001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '38', [CM_Sector_Name] = 'Mining & Mineral products' Where [Basic_Ind_Code] = 'IN010301001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '38', [CM_Sector_Name] = 'Mining & Mineral products' Where [Basic_Ind_Code] = 'IN010301002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '38', [CM_Sector_Name] = 'Mining & Mineral products' Where [Basic_Ind_Code] = 'IN010301003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '57', [CM_Sector_Name] = 'Steel' Where [Basic_Ind_Code] = 'IN010301004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '40', [CM_Sector_Name] = 'Non Ferrous Metals' Where [Basic_Ind_Code] = 'IN010302001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '40', [CM_Sector_Name] = 'Non Ferrous Metals' Where [Basic_Ind_Code] = 'IN010302002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '40', [CM_Sector_Name] = 'Non Ferrous Metals' Where [Basic_Ind_Code] = 'IN010302003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '40', [CM_Sector_Name] = 'Non Ferrous Metals' Where [Basic_Ind_Code] = 'IN010302004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '38', [CM_Sector_Name] = 'Mining & Mineral products' Where [Basic_Ind_Code] = 'IN010303001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '38', [CM_Sector_Name] = 'Mining & Mineral products' Where [Basic_Ind_Code] = 'IN010304001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '38', [CM_Sector_Name] = 'Mining & Mineral products' Where [Basic_Ind_Code] = 'IN010305001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '38', [CM_Sector_Name] = 'Mining & Mineral products' Where [Basic_Ind_Code] = 'IN010305002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN010401001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN010401002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN010401003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '5', [CM_Sector_Name] = 'Automobile' Where [Basic_Ind_Code] = 'IN020101001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '5', [CM_Sector_Name] = 'Automobile' Where [Basic_Ind_Code] = 'IN020101002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '5', [CM_Sector_Name] = 'Automobile' Where [Basic_Ind_Code] = 'IN020101003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '4', [CM_Sector_Name] = 'Auto Ancillaries' Where [Basic_Ind_Code] = 'IN020102001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '4', [CM_Sector_Name] = 'Auto Ancillaries' Where [Basic_Ind_Code] = 'IN020102002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '4', [CM_Sector_Name] = 'Auto Ancillaries' Where [Basic_Ind_Code] = 'IN020102003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '4', [CM_Sector_Name] = 'Auto Ancillaries' Where [Basic_Ind_Code] = 'IN020102004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '4', [CM_Sector_Name] = 'Auto Ancillaries' Where [Basic_Ind_Code] = 'IN020102005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '65', [CM_Sector_Name] = 'Tyres' Where [Basic_Ind_Code] = 'IN020102006'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '17', [CM_Sector_Name] = 'Consumer Durables' Where [Basic_Ind_Code] = 'IN020201001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '17', [CM_Sector_Name] = 'Consumer Durables' Where [Basic_Ind_Code] = 'IN020201002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '76', [CM_Sector_Name] = 'Electronics' Where [Basic_Ind_Code] = 'IN020201003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '17', [CM_Sector_Name] = 'Consumer Durables' Where [Basic_Ind_Code] = 'IN020201004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '20', [CM_Sector_Name] = 'Diamond' Where [Basic_Ind_Code] = 'IN020201005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '17', [CM_Sector_Name] = 'Consumer Durables' Where [Basic_Ind_Code] = 'IN020201006'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '17', [CM_Sector_Name] = 'Consumer Durables' Where [Basic_Ind_Code] = 'IN020201007'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '17', [CM_Sector_Name] = 'Consumer Durables' Where [Basic_Ind_Code] = 'IN020201008'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '35', [CM_Sector_Name] = 'Leather' Where [Basic_Ind_Code] = 'IN020201009'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '17', [CM_Sector_Name] = 'Consumer Durables' Where [Basic_Ind_Code] = 'IN020201010'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '48', [CM_Sector_Name] = 'Plastic products' Where [Basic_Ind_Code] = 'IN020201011'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '17', [CM_Sector_Name] = 'Consumer Durables' Where [Basic_Ind_Code] = 'IN020201012'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '13', [CM_Sector_Name] = 'Ceramic Products' Where [Basic_Ind_Code] = 'IN020201013'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '17', [CM_Sector_Name] = 'Consumer Durables' Where [Basic_Ind_Code] = 'IN020201014'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '43', [CM_Sector_Name] = 'Paints/Varnish' Where [Basic_Ind_Code] = 'IN020201015'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '17', [CM_Sector_Name] = 'Consumer Durables' Where [Basic_Ind_Code] = 'IN020201016'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '17', [CM_Sector_Name] = 'Consumer Durables' Where [Basic_Ind_Code] = 'IN020201017'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '50', [CM_Sector_Name] = 'Readymade Garments/ Apparells' Where [Basic_Ind_Code] = 'IN020301001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '62', [CM_Sector_Name] = 'Textiles' Where [Basic_Ind_Code] = 'IN020301002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '62', [CM_Sector_Name] = 'Textiles' Where [Basic_Ind_Code] = 'IN020301003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '37', [CM_Sector_Name] = 'Media - Print/Television/Radio' Where [Basic_Ind_Code] = 'IN020401001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '37', [CM_Sector_Name] = 'Media - Print/Television/Radio' Where [Basic_Ind_Code] = 'IN020401002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '37', [CM_Sector_Name] = 'Media - Print/Television/Radio' Where [Basic_Ind_Code] = 'IN020401003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '37', [CM_Sector_Name] = 'Media - Print/Television/Radio' Where [Basic_Ind_Code] = 'IN020401004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '24', [CM_Sector_Name] = 'Entertainment' Where [Basic_Ind_Code] = 'IN020402001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '24', [CM_Sector_Name] = 'Entertainment' Where [Basic_Ind_Code] = 'IN020402002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '24', [CM_Sector_Name] = 'Entertainment' Where [Basic_Ind_Code] = 'IN020402003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '24', [CM_Sector_Name] = 'Entertainment' Where [Basic_Ind_Code] = 'IN020402004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '37', [CM_Sector_Name] = 'Media - Print/Television/Radio' Where [Basic_Ind_Code] = 'IN020403001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '51', [CM_Sector_Name] = 'Realty' Where [Basic_Ind_Code] = 'IN020501001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '51', [CM_Sector_Name] = 'Realty' Where [Basic_Ind_Code] = 'IN020501002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '81', [CM_Sector_Name] = 'Real Estate Investment Trusts' Where [Basic_Ind_Code] = 'IN020501003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '31', [CM_Sector_Name] = 'Hotels & Restaurants' Where [Basic_Ind_Code] = 'IN020601001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '31', [CM_Sector_Name] = 'Hotels & Restaurants' Where [Basic_Ind_Code] = 'IN020601002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN020601003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN020601004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN020601005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '15', [CM_Sector_Name] = 'Computer Education' Where [Basic_Ind_Code] = 'IN020602001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '15', [CM_Sector_Name] = 'Computer Education' Where [Basic_Ind_Code] = 'IN020602002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN020602003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN020602004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '54', [CM_Sector_Name] = 'Retail' Where [Basic_Ind_Code] = 'IN020603001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '54', [CM_Sector_Name] = 'Retail' Where [Basic_Ind_Code] = 'IN020603002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '54', [CM_Sector_Name] = 'Retail' Where [Basic_Ind_Code] = 'IN020603003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '80', [CM_Sector_Name] = 'E-Commerce/App based Aggregator' Where [Basic_Ind_Code] = 'IN020603004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '54', [CM_Sector_Name] = 'Retail' Where [Basic_Ind_Code] = 'IN020603005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '54', [CM_Sector_Name] = 'Retail' Where [Basic_Ind_Code] = 'IN020603006'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '19', [CM_Sector_Name] = 'Crude Oil & Natural Gas' Where [Basic_Ind_Code] = 'IN030101001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '19', [CM_Sector_Name] = 'Crude Oil & Natural Gas' Where [Basic_Ind_Code] = 'IN030101002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '28', [CM_Sector_Name] = 'Gas Distribution' Where [Basic_Ind_Code] = 'IN030101003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '19', [CM_Sector_Name] = 'Crude Oil & Natural Gas' Where [Basic_Ind_Code] = 'IN030101004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '19', [CM_Sector_Name] = 'Crude Oil & Natural Gas' Where [Basic_Ind_Code] = 'IN030102001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '19', [CM_Sector_Name] = 'Crude Oil & Natural Gas' Where [Basic_Ind_Code] = 'IN030102002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '19', [CM_Sector_Name] = 'Crude Oil & Natural Gas' Where [Basic_Ind_Code] = 'IN030102003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '19', [CM_Sector_Name] = 'Crude Oil & Natural Gas' Where [Basic_Ind_Code] = 'IN030102004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '52', [CM_Sector_Name] = 'Refineries' Where [Basic_Ind_Code] = 'IN030103001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '19', [CM_Sector_Name] = 'Crude Oil & Natural Gas' Where [Basic_Ind_Code] = 'IN030103002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '52', [CM_Sector_Name] = 'Refineries' Where [Basic_Ind_Code] = 'IN030104001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '23', [CM_Sector_Name] = 'Edible Oil' Where [Basic_Ind_Code] = 'IN040101001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '59', [CM_Sector_Name] = 'Sugar' Where [Basic_Ind_Code] = 'IN040101002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040101003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '47', [CM_Sector_Name] = 'Plantation & Plantation Products' Where [Basic_Ind_Code] = 'IN040101004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '3', [CM_Sector_Name] = 'Alcoholic Beverages' Where [Basic_Ind_Code] = 'IN040102001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040102002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '63', [CM_Sector_Name] = 'Tobacco Products' Where [Basic_Ind_Code] = 'IN040103001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040104001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040104002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040104003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040104004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040105001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040106001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040106002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040106003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040106004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '27', [CM_Sector_Name] = 'FMCG' Where [Basic_Ind_Code] = 'IN040107001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050101001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050101002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050101003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050101004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050101005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050101006'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '6', [CM_Sector_Name] = 'Banks' Where [Basic_Ind_Code] = 'IN050102001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '6', [CM_Sector_Name] = 'Banks' Where [Basic_Ind_Code] = 'IN050102002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '6', [CM_Sector_Name] = 'Banks' Where [Basic_Ind_Code] = 'IN050102003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050103001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050103002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050103003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '18', [CM_Sector_Name] = 'Credit Rating Agencies' Where [Basic_Ind_Code] = 'IN050103004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050103005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '58', [CM_Sector_Name] = 'Stock/ Commodity Brokers' Where [Basic_Ind_Code] = 'IN050103006'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050103007'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '67', [CM_Sector_Name] = 'Insurance' Where [Basic_Ind_Code] = 'IN050104001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '67', [CM_Sector_Name] = 'Insurance' Where [Basic_Ind_Code] = 'IN050104002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '67', [CM_Sector_Name] = 'Insurance' Where [Basic_Ind_Code] = 'IN050104003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '67', [CM_Sector_Name] = 'Insurance' Where [Basic_Ind_Code] = 'IN050104004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '26', [CM_Sector_Name] = 'Finance' Where [Basic_Ind_Code] = 'IN050105001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '46', [CM_Sector_Name] = 'Pharmaceuticals' Where [Basic_Ind_Code] = 'IN060101001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '30', [CM_Sector_Name] = 'Healthcare' Where [Basic_Ind_Code] = 'IN060101002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '30', [CM_Sector_Name] = 'Healthcare' Where [Basic_Ind_Code] = 'IN060102001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '30', [CM_Sector_Name] = 'Healthcare' Where [Basic_Ind_Code] = 'IN060103001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '30', [CM_Sector_Name] = 'Healthcare' Where [Basic_Ind_Code] = 'IN060103002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '30', [CM_Sector_Name] = 'Healthcare' Where [Basic_Ind_Code] = 'IN060103003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '16', [CM_Sector_Name] = 'Construction' Where [Basic_Ind_Code] = 'IN070101001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '16', [CM_Sector_Name] = 'Construction' Where [Basic_Ind_Code] = 'IN070101002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '72', [CM_Sector_Name] = 'Engineering' Where [Basic_Ind_Code] = 'IN070201001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '5', [CM_Sector_Name] = 'Automobile' Where [Basic_Ind_Code] = 'IN070202001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '5', [CM_Sector_Name] = 'Automobile' Where [Basic_Ind_Code] = 'IN070202002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '5', [CM_Sector_Name] = 'Automobile' Where [Basic_Ind_Code] = 'IN070202003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '8', [CM_Sector_Name] = 'Capital Goods - Electrical Equipment' Where [Basic_Ind_Code] = 'IN070203001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '8', [CM_Sector_Name] = 'Capital Goods - Electrical Equipment' Where [Basic_Ind_Code] = 'IN070203002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '9', [CM_Sector_Name] = 'Capital Goods-Non Electrical Equipment' Where [Basic_Ind_Code] = 'IN070204001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '9', [CM_Sector_Name] = 'Capital Goods-Non Electrical Equipment' Where [Basic_Ind_Code] = 'IN070204002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '76', [CM_Sector_Name] = 'Electronics' Where [Basic_Ind_Code] = 'IN070204003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '9', [CM_Sector_Name] = 'Capital Goods-Non Electrical Equipment' Where [Basic_Ind_Code] = 'IN070204004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '77', [CM_Sector_Name] = 'Railways' Where [Basic_Ind_Code] = 'IN070204005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '55', [CM_Sector_Name] = 'Ship Building' Where [Basic_Ind_Code] = 'IN070204006'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '9', [CM_Sector_Name] = 'Capital Goods-Non Electrical Equipment' Where [Basic_Ind_Code] = 'IN070204007'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '9', [CM_Sector_Name] = 'Capital Goods-Non Electrical Equipment' Where [Basic_Ind_Code] = 'IN070205001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '66', [CM_Sector_Name] = 'Bearings' Where [Basic_Ind_Code] = 'IN070205002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '7', [CM_Sector_Name] = 'Cables' Where [Basic_Ind_Code] = 'IN070205003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '10', [CM_Sector_Name] = 'Castings' Where [Basic_Ind_Code] = 'IN070205004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '9', [CM_Sector_Name] = 'Capital Goods-Non Electrical Equipment' Where [Basic_Ind_Code] = 'IN070205005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '9', [CM_Sector_Name] = 'Capital Goods-Non Electrical Equipment' Where [Basic_Ind_Code] = 'IN070205006'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '8', [CM_Sector_Name] = 'Capital Goods - Electrical Equipment' Where [Basic_Ind_Code] = 'IN070205007'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '42', [CM_Sector_Name] = 'Packaging' Where [Basic_Ind_Code] = 'IN070205008'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '48', [CM_Sector_Name] = 'Plastic products' Where [Basic_Ind_Code] = 'IN070205009'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '53', [CM_Sector_Name] = 'Refractories' Where [Basic_Ind_Code] = 'IN070205010'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '9', [CM_Sector_Name] = 'Capital Goods-Non Electrical Equipment' Where [Basic_Ind_Code] = 'IN070205011'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '9', [CM_Sector_Name] = 'Capital Goods-Non Electrical Equipment' Where [Basic_Ind_Code] = 'IN070205012'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '29', [CM_Sector_Name] = 'Glass & Glass Products' Where [Basic_Ind_Code] = 'IN070205013'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '40', [CM_Sector_Name] = 'Non Ferrous Metals' Where [Basic_Ind_Code] = 'IN070205014'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '57', [CM_Sector_Name] = 'Steel' Where [Basic_Ind_Code] = 'IN070205015'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '34', [CM_Sector_Name] = 'IT - Software' Where [Basic_Ind_Code] = 'IN080101001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '34', [CM_Sector_Name] = 'IT - Software' Where [Basic_Ind_Code] = 'IN080101002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '34', [CM_Sector_Name] = 'IT - Software' Where [Basic_Ind_Code] = 'IN080102001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '72', [CM_Sector_Name] = 'Engineering' Where [Basic_Ind_Code] = 'IN080103001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '72', [CM_Sector_Name] = 'Engineering' Where [Basic_Ind_Code] = 'IN090101001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '2', [CM_Sector_Name] = 'Air Transport Service' Where [Basic_Ind_Code] = 'IN090102001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '36', [CM_Sector_Name] = 'Logistics' Where [Basic_Ind_Code] = 'IN090102002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '77', [CM_Sector_Name] = 'Railways' Where [Basic_Ind_Code] = 'IN090102003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '36', [CM_Sector_Name] = 'Logistics' Where [Basic_Ind_Code] = 'IN090102004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '56', [CM_Sector_Name] = 'Shipping' Where [Basic_Ind_Code] = 'IN090102005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '36', [CM_Sector_Name] = 'Logistics' Where [Basic_Ind_Code] = 'IN090102006'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '32', [CM_Sector_Name] = 'Infrastructure Developers & Operators' Where [Basic_Ind_Code] = 'IN090103001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '83', [CM_Sector_Name] = 'Marine Port & Services' Where [Basic_Ind_Code] = 'IN090103002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '32', [CM_Sector_Name] = 'Infrastructure Developers & Operators' Where [Basic_Ind_Code] = 'IN090103003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '64', [CM_Sector_Name] = 'Trading' Where [Basic_Ind_Code] = 'IN090104001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN090104002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN090104003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN090104004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN090104005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '61', [CM_Sector_Name] = 'Telecomm-Service' Where [Basic_Ind_Code] = 'IN100101001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '60', [CM_Sector_Name] = 'Telecomm Equipment & Infra Services' Where [Basic_Ind_Code] = 'IN100101002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '61', [CM_Sector_Name] = 'Telecomm-Service' Where [Basic_Ind_Code] = 'IN100101003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '60', [CM_Sector_Name] = 'Telecomm Equipment & Infra Services' Where [Basic_Ind_Code] = 'IN100102001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '49', [CM_Sector_Name] = 'Power Generation & Distribution' Where [Basic_Ind_Code] = 'IN110101001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '49', [CM_Sector_Name] = 'Power Generation & Distribution' Where [Basic_Ind_Code] = 'IN110101002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '49', [CM_Sector_Name] = 'Power Generation & Distribution' Where [Basic_Ind_Code] = 'IN110101003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '72', [CM_Sector_Name] = 'Engineering' Where [Basic_Ind_Code] = 'IN110201001'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN110201002'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '39', [CM_Sector_Name] = 'Miscellaneous' Where [Basic_Ind_Code] = 'IN110201003'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '21', [CM_Sector_Name] = 'Diversified' Where [Basic_Ind_Code] = 'IN110201004'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '21', [CM_Sector_Name] = 'Diversified' Where [Basic_Ind_Code] = 'IN110201005'
Update [Masters].[Industry_Classification] Set [CM_Sector_Code] = '21', [CM_Sector_Name] = 'Diversified' Where [Basic_Ind_Code] = 'IN120101001'





