USE [PMS_Base]
GO

/****** Object:  Table [Masters].[DebtSecurity] ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Masters].[DebtSecurity]') AND type in (N'U'))
DROP TABLE [Masters].[DebtSecurity]
GO

CREATE TABLE [Masters].[DebtSecurity](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	DebtSecurity_Id	int NOT NULL UNIQUE,
	Security_Name varchar(100) NOT NULL,
	ISIN varchar(12) NOT NULL,
	Exchange_1 varchar(6) NULL,
	Exchange_1_Local_Code varchar(50) NULL,
	Exchange_2 varchar(6),
	Exchange_2_Local_Code varchar(50),
	Exchange_3 varchar(6),
	Exchange_3_Local_Code varchar(50),
	Security_Type varchar(100) NOT NULL,
	Bond_Type_Code varchar(20) NOT NULL,
	Bond_Type	varchar(100) NOT NULL,
	Country varchar(2) NOT NULL,
	Bilav_Internal_Issuer_Id int NOT NULL,
	Bilav_Code varchar(50) NOT NULL,
	LEI	varchar(25),
	CIN	varchar(25),
	Issuer varchar(70) NOT NULL,
	Issue_Price	numeric(16,6),
	Issue_Date date,
	Maturity_Price numeric(16,6) NOT NULL,
	Maturity_Based_On varchar(10),
	Maturity_Benchmark_Index varchar(100),
	Maturity_Price_As_Perc numeric(16,6) NOT NULL,
	Is_Perpetual varchar(5),
	On_Tap_Indicator bit,
	Deemed_Allotment_Date date,
	Coupon_Type_Code varchar(10) NOT NULL,
	Coupon_Type varchar(70) NOT NULL,
	Interest_Payment_Frequency_Code varchar(10),
	Interest_Payment_Frequency varchar(70),
	Interest_Payout_1 date,
	Is_Cumulative bit,
	Compounding_Frequency_Code varchar(10),
	Compounding_Frequency varchar(70),
	Interest_Accrual_Convention_Code varchar(10),
	Interest_Accrual_Convention varchar(70),
	Min_Investment_Amount numeric(16,6),
	FRN_Index_Benchmark	varchar(10),
	FRN_Index_Benchmark_Desc varchar(100),
	Interest_Pay_Date_1	varchar(4),
	Interest_Pay_Date_2	varchar(4),
	Interest_Pay_Date_3	varchar(4),
	Interest_Pay_Date_4	varchar(4),
	Interest_Pay_Date_5	varchar(4),
	Interest_Pay_Date_6	varchar(4),
	Interest_Pay_Date_7	varchar(4),
	Interest_Pay_Date_8	varchar(4),
	Interest_Pay_Date_9	varchar(4),
	Interest_Pay_Date_10 varchar(4),
	Interest_Pay_Date_11 varchar(4),
	Interest_Pay_Date_12 varchar(4),
	Issuer_Type_Code varchar(10) NOT NULL,
	Issuer_Type	varchar(50) NOT NULL,
	Issue_Size numeric(36,6),
	Outstanding_Amount numeric(16,6),
	Outstanding_Amount_Date	date,
	Yield_At_Issue numeric(16,6),
	Maturity_Structure_Code	varchar(20) NOT NULL,
	Maturity_Structure varchar(50) NOT NULL,
	Convention_Method_Code varchar(10),
	Convention_Method varchar(10),
	Interest_BDC_Code varchar(10),
	Interest_BDC varchar(100),
	Is_Variable_Interest_Payment_Date bit NOT NULL,
	Interest_Commencement_Date date,
	Coupon_Cut_Off_Days	int,
	Coupon_Cut_Off_Day_Convention varchar(10),
	FRN_Type varchar(10),
	FRN_Interest_Adjustment_Frequency varchar(10),
	Markup numeric(16,6),
	Minimum_Interest_Rate numeric(16,6),
	Maximum_Interest_Rate numeric(16,6),
	Is_Guaranteed bit,
	Is_Secured bit,
	Security_Charge	varchar(10),
	Security_Collateral	bit,
	Tier int,
	Is_Upper bit,
	Is_Sub_Ordinate	bit,
	Is_Senior varchar(50),
	Is_Callable	bit NOT NULL,
	Is_Puttable	bit NOT NULL,
	Strip varchar(50),
	Is_Taxable bit,
	Latest_Applied_INTPY_Annual_Coupon_Rate	numeric(16,6),
	Latest_Applied_INTPY_Annual_Coupon_Rate_Date date,
	Bond_Notes varchar(2000),
	End_Use	varchar(2000),
	Initial_Fixing_Date	date,
	Initial_Fixing_Level varchar(100),
	Final_Fixing_Date date,
	Final_Fixing_Level varchar(100),
	PayOff_Condition varchar(100),
	Majority_Anchor_Investor varchar(100),
	Security_Cover_Ratio numeric(16,6),
	Margin_TopUp_Trigger varchar(100),
	Current_Yield numeric(16,6),
	Security_Presentation_Link varchar(500),
	Coupon_Reset_Event varchar(100),
	[MES_Code] [varchar](100),
	[Macro_Economic_Sector] [varchar](200),
	[Sect_Code] [varchar](100),
	[Sector] [varchar](200),
	[Ind_Code] [varchar](100),
	[Industry] [varchar](200),
	[Basic_Ind_Code] [varchar](100),
	[Basic_Industry] [varchar](200),
	[Is_Deleted] [bit] NOT NULL,
	[Created_By] [bigint] NOT NULL,
	[Created_Date] [datetime] NOT NULL,
	[Updated_By] [bigint],
	[Updated_Date] [datetime]
	PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	) ON [PRIMARY]
) ON [PRIMARY]
GO

